### ISSUE TITLE
Can't load web ui

### ISSUE THREAD

**Issue by Majobaga** [gurucomputing/headscale-ui#102] opened 2023-05-08 18:17 UTC
** Supporting Details **
Provide the following:
* Browser Version: Chrome Version 112.0.5615.138
* Headscale Version: 0.22.1
* Any Browser Errors (`control+shift+i` in chrome to see)

![Headscale UI issue](https://user-images.githubusercontent.com/64119420/236898629-b4b87d89-45d5-4438-872e-15a3e1dc6824.png)

**Describe the bug**
A clear and concise description of what the bug is. Screenshots if applicable.

The web ui was working when I got it set up initially but a few hours later when after I had connected my Pfsense and Android phone as nodes it wouldn't work anymore. I get a full white page when I go to the headscaleURL/web with the errors as shown by the attached image.

I'm running headscale and headscale-ui as docker containers and ngninx proxy manager as a reverse proxy. I had the configuration set up per the documentation and nothing really was changed. I have tried restarting the containers, npm, reinstalled the containers, changed the domain, network within portainer, ports, etc etc. I appreciate the help, thanks!

**Comment by routerino** [comment] 2023-05-10 12:21
CSP error means that the web page thinks its been modified. The bunch of 404 errors means that it isn't resolving the web application static files.

Your web application has either stopped being served or isn't being routed correctly by your reverse proxy. Try clearing cache or restarting your docker containers.

**Comment by Majobaga** [comment] 2023-05-10 19:54
Unfortunately I'm not as savyy about linux and docker to understand fully what to do and what's going on. I've restarted the containers, restarted npm, removed them and pulled new images, changed ports, changed the subdomain, nothing works. Now at least it's not doing the same thing, now it's fully giving me a 404 type error.

I've tried to do everything I can. I'm not being successful at getting it to work again. It's probably something I don't know about or something wrong I'm doing. But I have another 20 proxy hosts on nginx p m working fine and no issues. Any insight would be very much appreciated. And sorry for the ignorance. TY.

<img width="1214" alt="Screenshot 2023-05-10 155114" src="https://github.com/gurucomputing/headscale-ui/assets/64119420/44b039d6-c7d4-44e3-b93b-33bce1041c78">

**Comment by routerino** [comment] 2023-05-11 00:45
error 400 means bad request, it's still a disconnect somewhere between how nginx proxy manager is serving the site and how it is being presented. Bare in mind that the site is a statically hosted site. You can put a site that has `<html><body>hello world</body></html>` in the same spot, if it doesn't load `hello world` then you know it's a problem with the proxy configuration.

I did write a guide for [setting up headscale ui with caddy](https://blog.gurucomputing.com.au/s/blog/doc/configuring-the-headscale-ui-ZOmuv0dSwM) but that will only be limited use to troubleshoot nginx proxy manager.

**Comment by routerino** [comment] 2023-05-31 22:43
closing as stale, cannot reproduce.

**Closed by routerino** 2023-05-31 22:43 UTC
