### ISSUE TITLE
Can't rename device

### ISSUE THREAD

**Issue by dgoujard** [gurucomputing/headscale-ui#48] opened 2022-08-16 12:52 UTC
When i try to update a device name, I got this 501 error: 
`{"code":12, "message":"Method Not Allowed", "details":[]}`

**Comment by routerino** [comment] 2022-08-16 21:43
Method not allowed means the server denied the action. What's the according error message in the headscale logs? What version of headscale are you running?

**Comment by routerino** [comment] 2022-08-18 02:43
Going to close this, as there is no response and this sounds like an issue with headscale not being up to date.

**Comment by dgoujard** [comment] 2022-08-18 07:21
Hi, sorry for the delay, it's the last version of headscale: 0.16.2
I don't have log in the headscale container when i navigate in the headscale-ui (but i can see data on the interface)

**Comment by routerino** [comment] 2022-08-18 08:58
When you attempt to update the name, there will be a corresponding log in the headscale console in the command line. What does it say?

**Comment by routerino** [comment] 2022-08-18 09:53
Ah, actually I suspect you're encountering another CORS issue. are you running headscale-ui on the same subdomain? if not, are you letting through all of the following options in CORS?
`Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE"`

**Comment by dgoujard** [comment] 2022-08-18 10:14
It's the same domain but the POST url contain a // so it's my config i think. I check that

**Comment by routerino** [comment] 2022-08-18 23:34
possibly a duplicate of #49 , which has a fix next week (albeit I couldn't get chrome or firefox to complain about a trailing slash).

**Comment by dgoujard** [comment] 2022-08-19 13:37
Ok it's a issue in my setting, in the Headscale URL it was : `https://headscale.monndd/` when i change it to `https://headscale.monndd` it work !

**Comment by routerino** [comment] 2022-08-19 23:12
righto, should be fixed next release

**Closed by routerino** 2022-08-19 23:12 UTC
Labels: bug, duplicate
